name: awesome-reft
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - python=3.10.14=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.29.1
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anyio==4.3.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - cachetools==5.3.3
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - comm==0.2.2
    - contourpy==1.2.1
    - cycler==0.12.1
    - dacite==1.8.1
    - datasets==2.18.0
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - evaluate==0.4.1
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - filelock==3.13.3
    - flash-attn==2.5.6
    - fonttools==4.51.0
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gcsfs==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-api-core==2.18.0
    - google-auth==2.29.0
    - google-auth-oauthlib==1.2.0
    - google-cloud-core==2.4.1
    - google-cloud-storage==2.16.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.7.0
    - googleapis-common-protos==1.63.0
    - h11==0.14.0
    - htmlmin==0.1.12
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.20.3
    - idna==3.6
    - imagehash==4.3.1
    - ipykernel==6.29.4
    - ipython==8.23.0
    - ipywidgets==8.1.2
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.3.2
    - json5==0.9.24
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.6.1
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.4
    - jupyter-server==2.13.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.4
    - jupyterlab-widgets==3.0.10
    - kiwisolver==1.4.5
    - llvmlite==0.42.0
    - markupsafe==2.1.5
    - matplotlib==3.8.4
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - mizani==0.11.1
    - mpmath==1.3.0
    - multidict==6.0.5
    - multimethod==1.11.2
    - multiprocess==0.70.16
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.3
    - ninja==1.11.1.1
    - notebook==7.1.2
    - notebook-shim==0.2.4
    - numba==0.59.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - overrides==7.7.0
    - packaging==24.0
    - pandas==2.2.1
    - pandocfilters==1.5.1
    - parso==0.8.4
    - patsy==0.5.6
    - pexpect==4.9.0
    - phik==0.12.4
    - pillow==10.3.0
    - pip==23.3.1
    - platformdirs==4.2.0
    - plotnine==0.13.4
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - proto-plus==1.23.0
    - protobuf==4.25.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==15.0.2
    - pyarrow-hotfix==0.6
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycparser==2.22
    - pydantic==2.6.4
    - pydantic-core==2.16.3
    - pygments==2.17.2
    - pyparsing==3.1.2
    - pyreft==0.0.4
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyvene==0.1.1
    - pywavelets==1.6.0
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - referencing==0.34.0
    - regex==2023.12.25
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - responses==0.18.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.18.0
    - rsa==4.9
    - safetensors==0.4.2
    - scikit-learn==1.4.1.post1
    - scipy==1.11.4
    - seaborn==0.12.2
    - send2trash==1.8.3
    - sentencepiece==0.2.0
    - sentry-sdk==1.44.1
    - setproctitle==1.3.3
    - setuptools==68.2.2
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - statsmodels==0.14.1
    - sympy==1.12
    - terminado==0.18.1
    - threadpoolctl==3.4.0
    - tinycss2==1.2.1
    - tokenizers==0.15.2
    - tomli==2.0.1
    - torch==2.2.2
    - tornado==6.4
    - tqdm==4.66.2
    - traitlets==5.14.2
    - transformers==4.39.3
    - triton==2.2.0
    - typeguard==4.2.1
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.11.0
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==2.2.1
    - visions==0.7.6
    - wandb==0.16.6
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - wheel==0.41.2
    - widgetsnbextension==4.0.10
    - wordcloud==1.9.3
    - xxhash==3.4.1
    - yarl==1.9.4
    - ydata-profiling==4.7.0
prefix: /u/nlp/anaconda/main/anaconda3/envs/awesome-reft
